import { ReactNode } from 'react'

import '../styles/globals.css'

export const metadata = {
  title: 'CarSync',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <head />
      <body>
        {/* <Navbar /> */}
        <div className="main">
          <div className="gradient" />
        </div>
        <main className="app">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
